# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  venv:
    cmds:
      - |
        python -m venv --system-site-packages .venv
        source .venv/bin/activate
        pip install -r requirements.txt

  test:
    cmds:
      - python predictions.py /archive/dataset/plates/train-ita-03/*jpg
